//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContent2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PXWebContentEntities : DbContext
    {
        public PXWebContentEntities()
            : base("name=PXWebContentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_HttpRes> Tbl_HttpRes { get; set; }
        public virtual DbSet<Tbl_Link> Tbl_Link { get; set; }
        public virtual DbSet<Tbl_Proxy> Tbl_Proxy { get; set; }
    }
}
