//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContent2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Proxy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Proxy()
        {
            this.Tbl_HttpRes = new HashSet<Tbl_HttpRes>();
        }
    
        public int Id { get; set; }
        public string ProxyAdress { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HttpRes> Tbl_HttpRes { get; set; }
    }
}
