//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContent2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HttpRes
    {
        public int Id { get; set; }
        public int ProxyId { get; set; }
        public int LinkId { get; set; }
        public string HttpRes { get; set; }
    
        public virtual Tbl_Link Tbl_Link { get; set; }
        public virtual Tbl_Proxy Tbl_Proxy { get; set; }
    }
}
